# Prior to conda-forge, Copyright 2014-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "at-spi2-core" %}
{% set version = "2.58.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: dfdd3300da2783a21969ffade2889817fb7c1906a4ef92497eba65969b3dab5a

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('at-spi2-core', max_pin='x.x') }}
  ignore_run_exports_from:
    - zlib

requirements:
  build:
    - gettext
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - setuptools  # needed for gobject-introspection, for now
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - dbus
    - glib
    - gobject-introspection
    - libxml2-devel
    - xorg-libx11
    - xorg-libxi
    - xorg-libxtst
    - zlib
  run:
    - xorg-libx11
    - xorg-libxi
    - xorg-libxtst

test:
  commands:
    - test -f $PREFIX/include/at-spi-2.0/atspi/atspi.h
    - test -f $PREFIX/lib/libatspi${SHLIB_EXT}

about:
  home: http://www.gtk.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: D-Bus-based implementation of AT-SPI accessibility framework
  description: |
    This package includes the protocol definitions for the new D-Bus at-spi.

    Also included is the daemon necessary for forwarding device events and
    registering accessible applicaitions.
  dev_url: https://gitlab.gnome.org/GNOME/at-spi2-core

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
