# Prior to conda-forge, Copyright 2014-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "at-spi2-core" %}
{% set version = "2.38.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 84e36c3fe66862133f5fe229772b76aa2526e10de5014a3778f2fa46ce550da5

build:
  number: 3
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('at-spi2-core', max_pin='x.x') }}
  missing_dso_whitelist:
    - '*/libX11.so*'

requirements:
  build:
    - gettext
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - {{ compiler('c') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('libxi-devel') }}
    - {{ cdt('libxfixes-devel') }}
    - {{ cdt('libxtst-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }}
  host:
    - dbus
    - glib
    - gobject-introspection

test:
  commands:
    - test -f $PREFIX/include/at-spi-2.0/atspi/atspi.h
    - test -f $PREFIX/lib/libatspi${SHLIB_EXT}

about:
  home: http://www.gtk.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: D-Bus-based implementation of AT-SPI accessibility framework
  description: |
    This package includes the protocol definitions for the new D-Bus at-spi.

    Also included is the daemon necessary for forwarding device events and
    registering accessible applicaitions.
  dev_url: https://gitlab.gnome.org/GNOME/at-spi2-core

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
